"""
Report Viewer Component - Reusable Streamlit component for displaying reports.
Used across multiple pages to render research reports consistently.
"""
import streamlit as st
import json
import os
from typing import Optional
from datetime import datetime


def render_report_header(topic: str, metadata: dict = None):
    """Render the report header with topic and metadata."""
    st.markdown(f"<h1>{topic}</h1>", unsafe_allow_html=True)
    st.markdown(f"<p style='color:#6B7280; margin-top:-10px; margin-bottom:1.5rem;'>Generated by Research AI • {datetime.utcnow().strftime('%B %d, %Y')}</p>", unsafe_allow_html=True)

    if metadata:
        cols = st.columns(4)
        metrics = [
            ("Sources Analyzed", metadata.get("total_sources", "0")),
            ("Quality Score", f"{metadata.get('quality_score', 0):.1f}/10"),
            ("Credibility", f"{metadata.get('credibility', 0):.1%}"),
            ("Revisions", metadata.get("revision_count", 0)),
        ]
        
        for col, (label, value) in zip(cols, metrics):
            with col:
                st.metric(label, value)
        
        st.markdown("<br>", unsafe_allow_html=True)


def render_report_body(report_markdown: str):
    """Render the main report content."""
    if not report_markdown:
        st.info("No report content available.")
        return

    st.markdown("""
    <div style="
        background-color: #FFFFFF;
        border: 1px solid #E5E7EB;
        border-radius: 12px;
        padding: 3rem;
        box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);
        margin-bottom: 2rem;
    ">
    """, unsafe_allow_html=True)
    
    st.markdown(report_markdown, unsafe_allow_html=True)
    
    st.markdown("</div>", unsafe_allow_html=True)


def render_sources_section(sources: list):
    """Render sources in a clean list."""
    if not sources:
        return

    st.markdown("<h3>References</h3>", unsafe_allow_html=True)

    for i, url in enumerate(sources, 1):
        st.markdown(f"""
        <div style="background:#F9FAFB; border:1px solid #E5E7EB; border-radius:8px; padding:1rem; margin-bottom:0.5rem; display:flex; align-items:center;">
            <div style="background:#E5E7EB; color:#374151; border-radius:50%; min-width:24px; height:24px; display:flex; align-items:center; justify-content:center; font-size:0.8rem; font-weight:bold; margin-right:1rem;">{i}</div>
            <a href="{url}" target="_blank" style="color:#2563EB; text-decoration:none; word-break:break-all;">{url}</a>
        </div>
        """, unsafe_allow_html=True)


def render_agent_timeline(state_dict: dict):
    """Render a visual timeline of agent execution."""
    st.markdown("<h3>Behind the Scenes</h3>", unsafe_allow_html=True)

    agents = [
        ("Planner", "Created research plan", True),
        ("Researcher", f"Found {len(state_dict.get('sources', []))} sources", True),
        ("Section Writer", f"Wrote {state_dict.get('current_section_index', 0)} sections", True),
        ("Assembler", "Combined report", True),
        ("Critic", f"Score: {state_dict.get('critic_feedback', {}).get('score', 'N/A') if state_dict.get('critic_feedback') else 'N/A'}/10", True),
        ("Fact-Checker", "Verified claims", True),
    ]

    html = "<div style='position: relative; padding-left: 20px; border-left: 2px solid #E5E7EB; margin-left: 10px;'>"
    
    for i, (agent, action, done) in enumerate(agents):
        color = "#10B981" if done else "#D1D5DB"
        # Removing leading spaces to prevent Markdown code block rendering
        html += f'''
<div style="position: relative; margin-bottom: 1.5rem;">
    <div style="position: absolute; left: -27px; top: 12px; width: 12px; height: 12px; border-radius: 50%; background: {color}; border: 2px solid white;"></div>
    <div style="background: #FFFFFF; border: 1px solid #E2E8F0; border-radius: 8px; padding: 1rem; box-shadow: 0 1px 2px rgba(0,0,0,0.02);">
        <strong style="color:#0F172A; display:block; margin-bottom: 0.25rem;">{agent}</strong>
        <span style="color:#64748B; font-size: 0.9rem;">{action}</span>
    </div>
</div>
'''
        
    html += "</div>"
    st.markdown(html, unsafe_allow_html=True)


def render_export_buttons(
    report_markdown: str,
    topic: str,
    report_json: dict = None,
):
    """Render download buttons for various export formats."""
    st.markdown("<h3>Export</h3>", unsafe_allow_html=True)

    col1, col2, col3 = st.columns(3)

    with col1:
        if report_markdown:
            st.download_button(
                label="Download Markdown",
                data=report_markdown.encode("utf-8"),
                file_name=f"report_{topic[:30].replace(' ', '_')}.md",
                mime="text/markdown",
                use_container_width=True,
                key=f"dl_md_{hash(topic)}",
            )

    with col2:
        if report_json:
            st.download_button(
                label="Download JSON",
                data=json.dumps(report_json, indent=2, default=str).encode("utf-8"),
                file_name=f"report_{topic[:30].replace(' ', '_')}.json",
                mime="application/json",
                use_container_width=True,
                key=f"dl_json_{hash(topic)}",
            )

    with col3:
        if report_markdown:
            try:
                from src.utils.pdf_exporter import export_to_pdf
                pdf_path = export_to_pdf(report_markdown, topic)

                with open(pdf_path, "rb") as f:
                    pdf_bytes = f.read()

                st.download_button(
                    label="Download PDF",
                    data=pdf_bytes,
                    file_name=f"report_{topic[:30].replace(' ', '_')}.pdf",
                    mime="application/pdf",
                    use_container_width=True,
                    key=f"dl_pdf_{hash(topic)}",
                )
            except Exception as e:
                st.error(f"PDF generation failed: {e}")


def display_full_report(
    report_markdown: str,
    topic: str,
    sources: list = None,
    metadata: dict = None,
    state_dict: dict = None,
):
    """
    Master function: Render a complete report with all sections.
    Call this from any page that needs to show a report.
    """
    render_report_header(topic, metadata)

    tab1, tab2, tab3 = st.tabs(["Document", "Trace", "Export"])

    with tab1:
        render_report_body(report_markdown)

    with tab2:
        col1, col2 = st.columns([1, 1])
        with col1:
            if state_dict:
                render_agent_timeline(state_dict)
        with col2:
            if sources:
                render_sources_section(sources)

    with tab3:
        render_export_buttons(
            report_markdown=report_markdown,
            topic=topic,
            report_json={
                "topic": topic,
                "report": report_markdown,
                "sources": sources or [],
                "metadata": metadata or {},
                "generated_at": datetime.utcnow().isoformat(),
            },
        )