"""
Report Viewer Component - Reusable Streamlit component for displaying reports.
Used across multiple pages to render research reports consistently.
"""
import streamlit as st
import json
import os
from typing import Optional
from datetime import datetime


def render_report_header(topic: str, metadata: dict = None):
    """Render the report header with topic and metadata."""
    st.markdown(f"""
    <div style="
        background: linear-gradient(135deg, #1a1a2e, #16213e);
        padding: 1.5rem;
        border-radius: 10px;
        margin-bottom: 1rem;
        border-left: 5px solid #4CAF50;
    ">
        <h2 style="color: white; margin: 0;">📋 {topic}</h2>
        <p style="color: #aaa; margin: 0.5rem 0 0 0;">
            Research Report • Generated by Multi-Agent AI System
        </p>
    </div>
    """, unsafe_allow_html=True)

    if metadata:
        cols = st.columns(4)
        metrics = [
            ("🔗 Sources", metadata.get("total_sources", "N/A")),
            ("⭐ Quality", f"{metadata.get('quality_score', 0):.1f}/10"),
            ("✅ Credibility", f"{metadata.get('credibility', 0):.1%}"),
            ("🔄 Revisions", metadata.get("revision_count", 0)),
        ]
        for col, (label, value) in zip(cols, metrics):
            with col:
                st.metric(label, value)


def render_report_body(report_markdown: str):
    """Render the main report content."""
    if not report_markdown:
        st.warning("⚠️ No report content available.")
        return

    # Display markdown report
    st.markdown(report_markdown)


def render_sources_section(sources: list):
    """Render sources in an expandable section."""
    if not sources:
        return

    with st.expander(f"🔗 Sources ({len(sources)} total)", expanded=False):
        for i, url in enumerate(sources, 1):
            col1, col2 = st.columns([1, 10])
            with col1:
                st.markdown(f"**{i}.**")
            with col2:
                st.markdown(f"[{url}]({url})")
                st.caption(f"Source {i}")


def render_quality_badge(score: float) -> str:
    """Return HTML badge based on quality score."""
    if score >= 9:
        color, label = "#4CAF50", "Excellent"
    elif score >= 7:
        color, label = "#2196F3", "Good"
    elif score >= 5:
        color, label = "#FF9800", "Fair"
    else:
        color, label = "#F44336", "Poor"

    return f"""
    <span style="
        background: {color};
        color: white;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: bold;
    ">{label} ({score:.1f}/10)</span>
    """


def render_agent_timeline(state_dict: dict):
    """Render a visual timeline of agent execution."""
    st.markdown("### 🤖 Agent Execution Timeline")

    agents = [
        ("🗺️ Planner", "Created research plan", True),
        ("🔬 Researcher", f"Found {len(state_dict.get('sources', []))} sources", True),
        ("✍️ Writer", f"Generated report ({state_dict.get('revision_count', 0)} revisions)", True),
        ("🎭 Critic", f"Score: {state_dict.get('critic_feedback', {}).get('score', 'N/A') if state_dict.get('critic_feedback') else 'N/A'}/10", True),
        ("🔍 Fact-Checker", "Verified claims", True),
    ]

    for i, (agent, action, done) in enumerate(agents):
        icon = "✅" if done else "⏳"
        st.markdown(
            f"""
            <div style="display:flex; align-items:center; margin:8px 0; 
                        padding:10px; background:#1e2030; border-radius:8px;
                        border-left: 3px solid {'#4CAF50' if done else '#666'}">
                <span style="font-size:20px; margin-right:10px">{icon}</span>
                <div>
                    <strong style="color:#fafafa">{agent}</strong>
                    <br><small style="color:#aaa">{action}</small>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )


def render_export_buttons(
    report_markdown: str,
    topic: str,
    report_json: dict = None,
):
    """Render download buttons for various export formats."""
    st.markdown("### ⬇️ Export Report")

    col1, col2, col3 = st.columns(3)

    # Markdown download (always available)
    with col1:
        if report_markdown:
            st.download_button(
                label="📄 Download Markdown",
                data=report_markdown.encode("utf-8"),
                file_name=f"report_{topic[:30].replace(' ', '_')}.md",
                mime="text/markdown",
                use_container_width=True,
                key=f"dl_md_{hash(topic)}",
            )

    # JSON download
    with col2:
        if report_json:
            st.download_button(
                label="📊 Download JSON",
                data=json.dumps(report_json, indent=2, default=str).encode("utf-8"),
                file_name=f"report_{topic[:30].replace(' ', '_')}.json",
                mime="application/json",
                use_container_width=True,
                key=f"dl_json_{hash(topic)}",
            )

    # PDF generation
    with col3:
        if st.button(
            "📑 Generate PDF",
            use_container_width=True,
            key=f"gen_pdf_{hash(topic)}",
        ):
            with st.spinner("Generating PDF... (this may take a moment)"):
                try:
                    from src.utils.pdf_exporter import export_to_pdf
                    pdf_path = export_to_pdf(report_markdown, topic)

                    with open(pdf_path, "rb") as f:
                        pdf_bytes = f.read()

                    st.download_button(
                        label="⬇️ Download PDF",
                        data=pdf_bytes,
                        file_name=f"report_{topic[:30].replace(' ', '_')}.pdf",
                        mime="application/pdf",
                        use_container_width=True,
                        key=f"dl_pdf_{hash(topic)}",
                    )
                    st.success(f"✅ PDF ready!")

                except Exception as e:
                    st.error(f"PDF generation failed: {e}")
                    st.info("💡 Tip: Install WeasyPrint system dependencies")


def display_full_report(
    report_markdown: str,
    topic: str,
    sources: list = None,
    metadata: dict = None,
    state_dict: dict = None,
):
    """
    Master function: Render a complete report with all sections.
    Call this from any page that needs to show a report.
    """
    render_report_header(topic, metadata)

    tab1, tab2, tab3 = st.tabs(["📄 Report", "🔗 Sources & Timeline", "⬇️ Export"])

    with tab1:
        render_report_body(report_markdown)

    with tab2:
        if sources:
            render_sources_section(sources)
        if state_dict:
            st.markdown("---")
            render_agent_timeline(state_dict)

    with tab3:
        render_export_buttons(
            report_markdown=report_markdown,
            topic=topic,
            report_json={
                "topic": topic,
                "report": report_markdown,
                "sources": sources or [],
                "metadata": metadata or {},
                "generated_at": datetime.utcnow().isoformat(),
            },
        )