import markdown
from xhtml2pdf import pisa
import tempfile
import os

def export_to_pdf(markdown_content: str, topic: str) -> str:
    """
    Converts markdown content into a beautifully formatted academic PDF.
    Returns the path to the generated temporary PDF file.
    """
    # Convert markdown to HTML
    html_body = markdown.markdown(markdown_content, extensions=['tables', 'fenced_code'])
    
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            @page {{
                size: A4;
                margin: 2.5cm;
            }}
            body {{
                font-family: "Times New Roman", serif;
                font-size: 12pt;
                line-height: 1.6;
                color: #000000;
                text-align: justify;
            }}
            h1 {{
                font-size: 24pt;
                text-align: center;
                margin-bottom: 24pt;
                font-weight: bold;
            }}
            h2 {{
                font-size: 16pt;
                margin-top: 18pt;
                margin-bottom: 12pt;
                border-bottom: 1px solid #000;
                padding-bottom: 4pt;
            }}
            h3 {{
                font-size: 14pt;
                margin-top: 12pt;
                margin-bottom: 8pt;
            }}
            p {{
                margin-bottom: 12pt;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-bottom: 12pt;
            }}
            th, td {{
                border: 1px solid #000;
                padding: 6pt;
                text-align: left;
            }}
            pre {{
                background-color: #f5f5f5;
                padding: 10pt;
                font-family: "Courier New", monospace;
                font-size: 10pt;
            }}
            .cover-page {{
                text-align: center;
                margin-top: 150pt;
                page-break-after: always;
            }}
            .cover-title {{
                font-size: 28pt;
                font-weight: bold;
                margin-bottom: 20pt;
            }}
            .cover-subtitle {{
                font-size: 16pt;
                color: #555555;
            }}
        </style>
    </head>
    <body>
        <div class="cover-page">
            <div class="cover-title">{topic}</div>
            <div class="cover-subtitle">Generated by Research Intelligence AI</div>
            <br><br><br>
            <p>Comprehensive Academic Report</p>
        </div>
        {html_body}
    </body>
    </html>
    """
    
    # Save the PDF to a temporary file
    temp_dir = tempfile.gettempdir()
    pdf_path = os.path.join(temp_dir, f"report_{hash(topic)}.pdf")
    
    with open(pdf_path, "wb") as result_file:
        pisa_status = pisa.CreatePDF(
            src=html_template,
            dest=result_file
        )
        
    if pisa_status.err:
        raise Exception("Error generating PDF from Markdown/HTML")
        
    return pdf_path